# Generated by Django 4.2.1 on 2023-05-30 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criarConta', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cadastro', models.IntegerField(blank=True, null=True)),
                ('eol', models.IntegerField(blank=True, null=True)),
                ('nome_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_social', models.CharField(blank=True, max_length=100, null=True)),
                ('raca_cor', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('idade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('certidao_nascimento', models.CharField(blank=True, max_length=10, null=True)),
                ('folha', models.CharField(blank=True, max_length=10, null=True)),
                ('livro', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_certidao', models.IntegerField(blank=True, null=True)),
                ('rg', models.CharField(blank=True, max_length=27, null=True)),
                ('data_expedicao', models.DateField(blank=True, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=100, null=True)),
                ('necessidade_especial', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_completo_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('telefone_residencial', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone_celular', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone_recado', models.CharField(blank=True, max_length=15, null=True)),
                ('nome_telefone_recado', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_sanguineo', models.CharField(blank=True, max_length=10, null=True)),
                ('convenio', models.CharField(blank=True, max_length=100, null=True)),
                ('alergias', models.CharField(blank=True, max_length=100, null=True)),
                ('problemas_saude', models.CharField(blank=True, max_length=100, null=True)),
                ('tratamento_medico', models.CharField(blank=True, max_length=100, null=True)),
                ('restricao_ativfisica', models.CharField(blank=True, max_length=100, null=True)),
                ('lesao_fratura_cirurgia', models.CharField(blank=True, max_length=100, null=True)),
                ('foto3x4', models.ImageField(blank=True, upload_to='documentos/')),
                ('rg_usuario', models.FileField(blank=True, upload_to='documentos/')),
                ('cert_nasc_usuario', models.FileField(blank=True, upload_to='documentos/')),
                ('rg_responsavel', models.FileField(blank=True, upload_to='documentos/')),
                ('comprov_residencia', models.FileField(blank=True, upload_to='documentos/')),
                ('autorizacao', models.FileField(blank=True, upload_to='documentos/')),
                ('idfunc', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='criarConta.customuser')),
            ],
        ),
    ]
