# Generated by Django 4.2.1 on 2023-05-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criarUsuario', '0002_alter_usuario_eol_alter_usuario_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_certidao',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
