# Generated by Django 4.2.1 on 2024-04-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criarUsuario', '0004_alter_usuario_e_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='e_mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
